gText_Birch_IncomingCall::
	.string "INCOMING CALL\p"
	.string "$"

gText_Birch_CanYouHearMe::
	.string "-BZZT-\p"
	.string "...\p"
	.string "Hello?\p"
	.string "Can you hear me?\p"
	.string "-BZZT-\p"
	.string "It's PROFESSOR BIRCH...\p"
	.string "$"

gText_Birch_AhHello::
	.string "Ah, hello!\p"
	.string "It seems like the call had some\n"
	.string "connection problems.\p"
	.string "I can't really see you but I can\n"
	.string "hear you, so that's good enough!\p"
	.string "$"

gText_Birch_YourDad::
	.string "As you know, your dad asked me to\n"
	.string "help you with some work experience.\p"
	.string "Don't worry, I've got something in mind\n"
	.string "I  think you'll be excited about!\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "Friends, family, co-workers,\n"
	.string "companions in battle...\p"
	.string "These are just some of the bonds\n"
	.string "we share with them.\p"
	.string "And yet, there are still so many\n"
	.string "things we don't know about POKéMON.\p"
	.string "That's why I've devoted my life to\n"
	.string "studying them!\p"
	.string "But enough about me!\p"
	.string "$"

gText_Birch_TellMeAboutYourself::
	.string "Why don't you tell me about yourself?\p"
	.string "$"

gText_Birch_WhatsYourStyle::
	.string "What's your kind of style?"
	.string "$"

gText_Birch_NameYouGoBy::
	.string "Okay! I have your details here but\n"
	.string "do you have a name you like to go by?$"

gText_Birch_PlayerThen::
	.string "{PLAYER}{KUN}, then?$"

gText_Birch_WellPlayer::
	.string "Well, {PLAYER}{KUN}, I look forward\n"
	.string "to meeting you in person!\p"
	.string "I'll see you soon!\p"
	.string "$"

gText_Birch_CallEnded::
	.string "CALL ENDED"
	.string "$"