RivalsHouse_1F_EventScript_RivalMom::
	lock
	faceplayer
	msgbox RivalsHouse_1F_Text_RivalMomDefault, MSGBOX_DEFAULT
	release
	end

RivalsHouse_1F_Text_RivalMomDefault:
	.string "My husband has been even busier\n"
	.string "than usual recently.\p"
	.string "{RIVAL} does a lot to help\n"
	.string "out too.$"

RivalsHouse_1F_EventScript_RivalSibling::
	lock
	faceplayer
	msgbox RivalsHouse_1F_Text_RivalSiblingDefault, MSGBOX_DEFAULT
	release
	end

RivalsHouse_1F_Text_RivalSiblingDefault:
    .string "I wish I could go on a journey\n"
    .string "with POKéMON.\p"
    .string "Mum says it's dangerous and I\n"
    .string "need to wait until I'm older.$"

